import FokkerChallenge.PairT
import FokkerChallenge.BetaCheck

/-!
# `λλ0(λλ201)` is not a one-point basis

The term

```
T = λλ0(λλ201) = λx y. y (λu v. y v u)
```

is one of the four terms of `undecided_terms.json` whose one-point-basis status was open.
This file settles it in the negative: **no applicative combination of `T` βη-reduces to
`I = λx. x`** (`gen_not_betaEtaStar_I`), nor to `K` (`gen_not_betaEtaStar_K`), so `T` is not
a one-point basis (`not_basis_0_lamlam201`).

What is actually proved is sharper (`gen_betaEtaStar_normal`):

> the only βη-normal forms reachable from an applicative combination of `T` are the three
> terms `T₀ = T`, `T₁ = λy. y (λu v. y v u)` and `T₂ = λy. y (λu v. y v u) T₁`;
> every other combination is unsolvable.

Since `I` and `K` are βη-normal and differ from `T₀`, `T₁`, `T₂`, neither is reachable.

## The argument

*Collapse.*  `x` does not occur in the body of `T`, so `T M ⟶β T₁` for **every** `M`
(`betaStar_T0_app`).  Consequently the whole clone generated by `T` collapses onto very few
values.  Writing `⟨M⟩ = λu v. M v u` (`flipT`), the basic reductions are

```
T₀ M Γ  ⟶h  T₁ Γ            T₁ M Γ  ⟶h  M ⟨M⟩ Γ
T₂ M Γ  ⟶h  M ⟨M⟩ T₁ Γ      ⟨M⟩ P Q Γ  ↠h  M Q P Γ
```

*The multiplication table.*  With them one computes
`T₁ T₀ ↠βη T₁`, `T₁ T₁ ↠βη T₂` and `T₂ T₀ ↠βη T₂` (the β-parts are certified by
`betaChainCheck`, the two η-steps are given explicitly), while `T₁ T₂`, `T₂ T₁` and `T₂ T₂`
diverge.  This is exactly the table

```
  ·  | T₀ | T₁ | T₂
-----+----+----+----
  T₀ | T₁ | T₁ | T₁
  T₁ | T₁ | T₂ | ⊥
  T₂ | T₂ | ⊥  | ⊥
```

*Divergence.*  All three diverging products head reduce to `T₂ T₁ Γ`, and `T₂ T₁ Γ` head
reduces in eight steps to the state `T₁ ⟨⟨T₁⟩⟩ ⟨⟨T₁⟩⟩ Γ`.  The set of states
`⟨ᵃT₁⟩ ⟨ⁱT₁⟩ ⟨ʲT₁⟩ Γ` with `i, j ≥ 2` (`DivSt`) is closed under a non-empty head reduction
(`DivSt.transGen`), so by the head normalization theorem of
`FokkerChallenge.EnhancedCslib.HeadSN` none of these terms has a head normal form.

Crucially the divergence statement carries an **arbitrary stack** `Γ` of further arguments
(`NoHNFStack`).  This is what makes unsolvability closed under application here, and it
replaces the classical "appending arguments cannot rescue an unsolvable head" lemma, which
is not available in the library.

*The invariant.*  `Good M` says: `M` βη-reduces to one of `T₀`, `T₁`, `T₂`, or `M`
βη-reduces to a term that diverges with any stack.  `good_app` shows `Good` is closed under
application — the table above is exactly the case analysis — and `gen_good` propagates it
through the whole clone.  Finally, if a combination βη-reduced to a βη-normal form `N`,
confluence of βη (`confluent_beta_eta`) forces `N ∈ {T₀, T₁, T₂}` in the first case, and in
the second case it would give the diverging term a βη-normal form, hence a β-normal form
(`hasBetaEtaNF_iff_hasBetaNF`), hence a head normal form — a contradiction.
-/

namespace Cslib

namespace LambdaCalculus.LocallyNameless.Untyped.Term

/-! ## The three values -/

/-- `T₀ = λλ0(λλ201) = λx y. y (λu v. y v u)`. -/
def T0 : Term String := db! "λλ0(λλ201)"

/-- `T₁ = λ0(λλ201) = λy. y (λu v. y v u)`, the value of `T₀ M` for every `M`. -/
def T1 : Term String := db! "λ0(λλ201)"

/-- `T₂ = λy. y (λu v. y v u) T₁`. -/
def T2 : Term String := db! "λ0(λλ201)(λ0(λλ201))"

theorem lc_T0 : LC T0 := by rw [← lcAt_iff_LC]; decide

theorem lc_T1 : LC T1 := by rw [← lcAt_iff_LC]; decide

theorem lc_T2 : LC T2 := by rw [← lcAt_iff_LC]; decide

/-- `flipT M = λu v. M v u`. -/
def flipT (M : Term String) : Term String :=
  .abs (.abs (.app (.app M (.bvar 0)) (.bvar 1)))

/-- `flipN n M` is `flipT` applied `n` times to `M`. -/
def flipN : ℕ → Term String → Term String
  | 0, M => M
  | n + 1, M => flipT (flipN n M)

theorem lc_flipT {M : Term String} (hM : LC M) : LC (flipT M) := by
  refine .abs ∅ _ (fun x _ => ?_)
  simp only [open', openRec]
  rw [open_lc 1 (fvar x) M hM]
  refine .abs ∅ _ (fun y _ => ?_)
  simp only [open', openRec]
  rw [open_lc 0 (fvar y) M hM]
  exact .app (.app hM (.fvar y)) (.fvar x)

theorem lc_flipN (n : ℕ) {M : Term String} (hM : LC M) : LC (flipN n M) := by
  induction n with
  | zero => exact hM
  | succ n ih => exact lc_flipT ih

/-! ## The head steps -/

theorem headStep_T0 {M : Term String} (hM : LC M) : HeadStep (.app T0 M) T1 := by
  have h := HeadStep.beta (M := T1) (N := M) (by rw [show Term.abs T1 = T0 from rfl]; exact lc_T0) hM
  simp only [open'] at h
  rwa [open_lc 0 M T1 lc_T1] at h

theorem headStep_T1 {M : Term String} (hM : LC M) :
    HeadStep (.app T1 M) (.app M (flipT M)) := by
  have h := HeadStep.beta
    (M := (.app (.bvar 0) (.abs (.abs (.app (.app (.bvar 2) (.bvar 0)) (.bvar 1))))))
    (N := M) lc_T1 hM
  have he : (Term.app (.bvar 0) (.abs (.abs (.app (.app (.bvar 2) (.bvar 0)) (.bvar 1))))) ^ M
      = .app M (flipT M) := by
    simp only [open', openRec, flipT]
    simp
  rwa [he] at h

theorem headStep_T2 {M : Term String} (hM : LC M) :
    HeadStep (.app T2 M) (.app (.app M (flipT M)) T1) := by
  have h := HeadStep.beta
    (M := (.app (.app (.bvar 0) (.abs (.abs (.app (.app (.bvar 2) (.bvar 0)) (.bvar 1))))) T1))
    (N := M) lc_T2 hM
  have he : (Term.app (.app (.bvar 0)
        (.abs (.abs (.app (.app (.bvar 2) (.bvar 0)) (.bvar 1))))) T1) ^ M
      = .app (.app M (flipT M)) T1 := by
    simp only [open', openRec, flipT]
    rw [show (Term.openRec 0 M T1) = T1 from open_lc 0 M T1 lc_T1]
    simp
  rwa [he] at h

theorem headStep_flipT {M P : Term String} (hM : LC M) (hP : LC P) :
    HeadStep (.app (flipT M) P) (pairT M P) := by
  have h := HeadStep.beta (M := (.abs (.app (.app M (.bvar 0)) (.bvar 1)))) (N := P)
    (lc_flipT hM) hP
  have he : (Term.abs (.app (.app M (.bvar 0)) (.bvar 1))) ^ P = pairT M P := by
    simp only [open', openRec, pairT]
    simp [open_lc 1 P M hM]
  rwa [he] at h

/-! ## Head steps with a stack of arguments -/

theorem headStep_T0_apps {M : Term String} (hM : LC M) (Γ : List (Term String))
    (hΓ : ∀ t ∈ Γ, LC t) : HeadStep (multiApp T0 (M :: Γ)) (multiApp T1 Γ) :=
  headStep_apps (headStep_T0 hM) (by rintro ⟨⟩) Γ hΓ

theorem headStep_T1_apps {M : Term String} (hM : LC M) (Γ : List (Term String))
    (hΓ : ∀ t ∈ Γ, LC t) : HeadStep (multiApp T1 (M :: Γ)) (multiApp M (flipT M :: Γ)) :=
  headStep_apps (headStep_T1 hM) (by rintro ⟨⟩) Γ hΓ

theorem headStep_T2_apps {M : Term String} (hM : LC M) (Γ : List (Term String))
    (hΓ : ∀ t ∈ Γ, LC t) : HeadStep (multiApp T2 (M :: Γ)) (multiApp M (flipT M :: T1 :: Γ)) :=
  headStep_apps (headStep_T2 hM) (by rintro ⟨⟩) Γ hΓ

theorem headStepStar_flipT_apps {M P Q : Term String} (hM : LC M) (hP : LC P) (hQ : LC Q)
    (Γ : List (Term String)) (hΓ : ∀ t ∈ Γ, LC t) :
    HeadStepStar (multiApp (flipT M) (P :: Q :: Γ)) (multiApp M (Q :: P :: Γ)) := by
  have h1 : HeadStep (multiApp (flipT M) (P :: Q :: Γ)) (multiApp (pairT M P) (Q :: Γ)) :=
    headStep_apps (headStep_flipT hM hP) (by rintro ⟨⟩) (Q :: Γ)
      (by intro t ht; rcases List.mem_cons.mp ht with rfl | ht; exacts [hQ, hΓ t ht])
  have h2 : HeadStep (multiApp (pairT M P) (Q :: Γ)) (multiApp M (Q :: P :: Γ)) :=
    headStep_apps (headStep_pairT hM hP hQ) (by rintro ⟨⟩) Γ hΓ
  exact .head h1 (.single h2)

/-! ## Divergence -/

/-- The diverging states: `flipⁿ T₁` applied to `flipⁱ T₁`, `flipʲ T₁` and an arbitrary
stack, with `i, j ≥ 2`. -/
def divState (a i j : ℕ) (Γ : List (Term String)) : Term String :=
  multiApp (flipN a T1) (flipN i T1 :: flipN j T1 :: Γ)

/-- The predicate cutting out the diverging states. -/
def DivSt (M : Term String) : Prop :=
  ∃ (a i j : ℕ) (Γ : List (Term String)),
    2 ≤ i ∧ 2 ≤ j ∧ (∀ t ∈ Γ, LC t) ∧ M = divState a i j Γ

/-- **Every diverging state head reduces, in at least one step, to a diverging state.** -/
theorem DivSt.transGen {M : Term String} (h : DivSt M) :
    ∃ N, Relation.TransGen HeadStep M N ∧ DivSt N := by
  obtain ⟨a, i, j, Γ, hi, hj, hΓ, rfl⟩ := h
  have hlcΓ : ∀ t ∈ (flipN j T1 :: Γ), LC t := by
    intro t ht
    rcases List.mem_cons.mp ht with rfl | ht
    exacts [lc_flipN j lc_T1, hΓ t ht]
  cases a with
  | zero =>
      refine ⟨divState i (i + 1) j Γ, Relation.TransGen.single ?_,
        ⟨i, i + 1, j, Γ, by omega, hj, hΓ, rfl⟩⟩
      exact headStep_T1_apps (lc_flipN i lc_T1) _ hlcΓ
  | succ a =>
      refine ⟨divState a j i Γ, ?_, ⟨a, j, i, Γ, hj, hi, hΓ, rfl⟩⟩
      have h1 : HeadStep (divState (a + 1) i j Γ)
          (multiApp (pairT (flipN a T1) (flipN i T1)) (flipN j T1 :: Γ)) :=
        headStep_apps (headStep_flipT (lc_flipN a lc_T1) (lc_flipN i lc_T1)) (by rintro ⟨⟩)
          (flipN j T1 :: Γ) hlcΓ
      have h2 : HeadStep (multiApp (pairT (flipN a T1) (flipN i T1)) (flipN j T1 :: Γ))
          (divState a j i Γ) :=
        headStep_apps (headStep_pairT (lc_flipN a lc_T1) (lc_flipN i lc_T1)
          (lc_flipN j lc_T1)) (by rintro ⟨⟩) Γ hΓ
      exact Relation.TransGen.head h1 (Relation.TransGen.single h2)

/-- A term that head reduces to a diverging state has no head normal form. -/
theorem not_hasHNF_of_divSt {M N : Term String} (h : HeadStepStar M N) (hN : DivSt N) :
    ¬ HasHNF M :=
  not_hasHNF_of_reaches (fun _ hM => DivSt.transGen hM) h hN

/-! ## Transfer along head reduction -/

/-! ## The three diverging products -/

/-- The entry into the diverging states: `T₂ T₁ Γ` head reduces in eight steps to the
diverging state `T₁ ⟨⟨T₁⟩⟩ ⟨⟨T₁⟩⟩ Γ`. -/
theorem headStepStar_T2T1 (Γ : List (Term String)) (hΓ : ∀ t ∈ Γ, LC t) :
    HeadStepStar (multiApp (.app T2 T1) Γ) (divState 0 2 2 Γ) := by
  have hlc1 : LC (flipN 1 T1) := lc_flipN 1 lc_T1
  have hlc2 : LC (flipN 2 T1) := lc_flipN 2 lc_T1
  have hΓ1 : ∀ t ∈ (T1 :: Γ), LC t := by
    intro t ht; rcases List.mem_cons.mp ht with rfl | ht; exacts [lc_T1, hΓ t ht]
  have hΓ2 : ∀ t ∈ (flipN 2 T1 :: Γ), LC t := by
    intro t ht; rcases List.mem_cons.mp ht with rfl | ht; exacts [hlc2, hΓ t ht]
  have s1 : HeadStep (multiApp T2 (T1 :: Γ)) (multiApp T1 (flipN 1 T1 :: T1 :: Γ)) :=
    headStep_T2_apps lc_T1 Γ hΓ
  have s2 : HeadStep (multiApp T1 (flipN 1 T1 :: T1 :: Γ))
      (multiApp (flipN 1 T1) (flipN 2 T1 :: T1 :: Γ)) :=
    headStep_T1_apps hlc1 (T1 :: Γ) hΓ1
  have s3 : HeadStepStar (multiApp (flipN 1 T1) (flipN 2 T1 :: T1 :: Γ))
      (multiApp T1 (T1 :: flipN 2 T1 :: Γ)) :=
    headStepStar_flipT_apps lc_T1 hlc2 lc_T1 Γ hΓ
  have s4 : HeadStep (multiApp T1 (T1 :: flipN 2 T1 :: Γ))
      (multiApp T1 (flipN 1 T1 :: flipN 2 T1 :: Γ)) :=
    headStep_T1_apps lc_T1 (flipN 2 T1 :: Γ) hΓ2
  have s5 : HeadStep (multiApp T1 (flipN 1 T1 :: flipN 2 T1 :: Γ))
      (multiApp (flipN 1 T1) (flipN 2 T1 :: flipN 2 T1 :: Γ)) :=
    headStep_T1_apps hlc1 (flipN 2 T1 :: Γ) hΓ2
  have s6 : HeadStepStar (multiApp (flipN 1 T1) (flipN 2 T1 :: flipN 2 T1 :: Γ))
      (divState 0 2 2 Γ) :=
    headStepStar_flipT_apps lc_T1 hlc2 hlc2 Γ hΓ
  exact (((((Relation.ReflTransGen.single s1).tail s2).trans s3).tail s4).tail s5).trans s6

theorem divSt_022 (Γ : List (Term String)) (hΓ : ∀ t ∈ Γ, LC t) : DivSt (divState 0 2 2 Γ) :=
  ⟨0, 2, 2, Γ, le_refl 2, le_refl 2, hΓ, rfl⟩

/-- **`T₂ T₁` diverges, with any stack of arguments.** -/
theorem noHNFStack_T2T1 : NoHNFStack (.app T2 T1) := fun Γ hΓ =>
  not_hasHNF_of_divSt (headStepStar_T2T1 Γ hΓ) (divSt_022 Γ hΓ)

/-- **`T₁ T₂` diverges, with any stack of arguments.** -/
theorem noHNFStack_T1T2 : NoHNFStack (.app T1 T2) := by
  intro Γ hΓ
  have hlc1 : LC (flipT T2) := lc_flipT lc_T2
  have hlc2 : LC (flipT (flipT T2)) := lc_flipT hlc1
  have s1 : HeadStep (multiApp T1 (T2 :: Γ)) (multiApp T2 (flipT T2 :: Γ)) :=
    headStep_T1_apps lc_T2 Γ hΓ
  have s2 : HeadStep (multiApp T2 (flipT T2 :: Γ))
      (multiApp (flipT T2) (flipT (flipT T2) :: T1 :: Γ)) :=
    headStep_T2_apps hlc1 Γ hΓ
  have s3 : HeadStepStar (multiApp (flipT T2) (flipT (flipT T2) :: T1 :: Γ))
      (multiApp T2 (T1 :: flipT (flipT T2) :: Γ)) :=
    headStepStar_flipT_apps lc_T2 hlc2 lc_T1 Γ hΓ
  have hΓ' : ∀ t ∈ (flipT (flipT T2) :: Γ), LC t := by
    intro t ht; rcases List.mem_cons.mp ht with rfl | ht; exacts [hlc2, hΓ t ht]
  exact not_hasHNF_of_headStepStar
    (((Relation.ReflTransGen.single s1).tail s2).trans s3)
    (noHNFStack_T2T1 (flipT (flipT T2) :: Γ) hΓ')

/-- **`T₂ T₂` diverges, with any stack of arguments.** -/
theorem noHNFStack_T2T2 : NoHNFStack (.app T2 T2) := by
  intro Γ hΓ
  have hlc1 : LC (flipT T2) := lc_flipT lc_T2
  have hlc2 : LC (flipT (flipT T2)) := lc_flipT hlc1
  have hΓ1 : ∀ t ∈ (T1 :: Γ), LC t := by
    intro t ht; rcases List.mem_cons.mp ht with rfl | ht; exacts [lc_T1, hΓ t ht]
  have s1 : HeadStep (multiApp T2 (T2 :: Γ)) (multiApp T2 (flipT T2 :: T1 :: Γ)) :=
    headStep_T2_apps lc_T2 Γ hΓ
  have s2 : HeadStep (multiApp T2 (flipT T2 :: T1 :: Γ))
      (multiApp (flipT T2) (flipT (flipT T2) :: T1 :: T1 :: Γ)) :=
    headStep_T2_apps hlc1 (T1 :: Γ) hΓ1
  have s3 : HeadStepStar (multiApp (flipT T2) (flipT (flipT T2) :: T1 :: T1 :: Γ))
      (multiApp T2 (T1 :: flipT (flipT T2) :: T1 :: Γ)) :=
    headStepStar_flipT_apps lc_T2 hlc2 lc_T1 (T1 :: Γ) hΓ1
  have hΓ' : ∀ t ∈ (flipT (flipT T2) :: T1 :: Γ), LC t := by
    intro t ht
    rcases List.mem_cons.mp ht with rfl | ht
    · exact hlc2
    · exact hΓ1 t ht
  exact not_hasHNF_of_headStepStar
    (((Relation.ReflTransGen.single s1).tail s2).trans s3)
    (noHNFStack_T2T1 (flipT (flipT T2) :: T1 :: Γ) hΓ')

/-- If `N` diverges with any stack, so does `T₁ N`. -/
theorem noHNFStack_T1_app {N : Term String} (hN : LC N) (h : NoHNFStack N) :
    NoHNFStack (.app T1 N) := by
  intro Γ hΓ
  have hΓ' : ∀ t ∈ (flipT N :: Γ), LC t := by
    intro t ht; rcases List.mem_cons.mp ht with rfl | ht; exacts [lc_flipT hN, hΓ t ht]
  exact not_hasHNF_of_headStepStar
    (Relation.ReflTransGen.single (headStep_T1_apps hN Γ hΓ)) (h (flipT N :: Γ) hΓ')

/-- If `N` diverges with any stack, so does `T₂ N`. -/
theorem noHNFStack_T2_app {N : Term String} (hN : LC N) (h : NoHNFStack N) :
    NoHNFStack (.app T2 N) := by
  intro Γ hΓ
  have hΓ' : ∀ t ∈ (flipT N :: T1 :: Γ), LC t := by
    intro t ht
    rcases List.mem_cons.mp ht with rfl | ht
    · exact lc_flipT hN
    · rcases List.mem_cons.mp ht with rfl | ht
      exacts [lc_T1, hΓ t ht]
  exact not_hasHNF_of_headStepStar
    (Relation.ReflTransGen.single (headStep_T2_apps hN Γ hΓ)) (h (flipT N :: T1 :: Γ) hΓ')

/-- Diverging with any stack is inherited by applications. -/
theorem noHNFStack_app {M N : Term String} (h : NoHNFStack M) (hN : LC N) :
    NoHNFStack (.app M N) := by
  intro Γ hΓ
  refine h (N :: Γ) ?_
  intro t ht; rcases List.mem_cons.mp ht with rfl | ht; exacts [hN, hΓ t ht]

/-! ## The multiplication table

`T₀` absorbs its argument, `T₁ T₀ = T₁`, `T₁ T₁ = T₂` and `T₂ T₀ = T₂` (the last two
βη-equalities really need an η-step). -/

/-- `C₁ = λw. T₁ w (λu v. T₁ u v)`, the β-normal form of `T₁ T₁`. -/
def C1 : Term String := db! "λ(λ0(λλ201))0(λλ(λ0(λλ201))10)"

/-- `C₂ = λw. T₁ w (λu. T₁ u)`, one η-step out of `C₁`. -/
def C2 : Term String := db! "λ(λ0(λλ201))0(λ(λ0(λλ201))0)"

/-- `C₃ = λw. T₁ w T₁`, one further η-step. -/
def C3 : Term String := db! "λ(λ0(λλ201))0(λ0(λλ201))"

/-- `T₀ M ⟶β T₁` for every locally closed `M`: `T₀` discards its argument. -/
theorem betaStar_T0_app {M : Term String} (hM : LC M) : (Term.app T0 M) ↠βᶠ T1 :=
  Relation.ReflTransGen.single (headStep_T0 hM).toFullBeta

/-- The two-step β-reduction `T₁ T₀ ↠β T₁`. -/
def chainT1T0 : List (Term String) :=
  [ db! "(λ0(λλ201))(λλ0(λλ201))"
  , db! "(λλ0(λλ201))(λλ(λλ0(λλ201))01)"
  , db! "λ0(λλ201)" ]

set_option maxRecDepth 100000 in
theorem chainT1T0_check : betaChainCheck chainT1T0 = true := by decide

theorem betaStar_T1T0 : (Term.app T1 T0) ↠βᶠ T1 :=
  betaChainCheck_sound chainT1T0 _ _ rfl rfl chainT1T0_check

/-- The five-step β-reduction `T₁ T₁ ↠β C₁`. -/
def chainT1T1 : List (Term String) :=
  [ db! "(λ0(λλ201))(λ0(λλ201))"
  , db! "(λ0(λλ201))(λλ(λ0(λλ201))01)"
  , db! "(λλ(λ0(λλ201))01)(λλ(λλ(λ0(λλ201))01)01)"
  , db! "λ(λ0(λλ201))0(λλ(λλ(λ0(λλ201))01)01)"
  , db! "λ(λ0(λλ201))0(λλ(λ(λ0(λλ201))01)1)"
  , db! "λ(λ0(λλ201))0(λλ(λ0(λλ201))10)" ]

set_option maxRecDepth 100000 in
theorem chainT1T1_check : betaChainCheck chainT1T1 = true := by decide

theorem betaStar_T1T1_C1 : (Term.app T1 T1) ↠βᶠ C1 :=
  betaChainCheck_sound chainT1T1 _ _ rfl rfl chainT1T1_check

/-- The η-step `C₁ ⟶η C₂`: the inner `λv. (T₁ u) v` collapses. -/
theorem fullEta_C1_C2 : FullEta C1 C2 := by
  refine Xi.abs ∅ (fun x _ => ?_)
  simp only [open', openRec]
  refine Xi.appL (.app lc_T1 (.fvar x)) (Xi.abs ∅ (fun y _ => ?_))
  simp only [open', openRec]
  exact Xi.base (Eta.eta (.app lc_T1 (.fvar y)))

/-- The η-step `C₂ ⟶η C₃`: the remaining `λu. T₁ u` collapses to `T₁`. -/
theorem fullEta_C2_C3 : FullEta C2 C3 := by
  refine Xi.abs ∅ (fun x _ => ?_)
  simp only [open', openRec]
  exact Xi.appL (.app lc_T1 (.fvar x)) (Xi.base (Eta.eta lc_T1))

/-- The one-step β-reduction `C₃ ↠β T₂`. -/
def chainC3T2 : List (Term String) :=
  [ db! "λ(λ0(λλ201))0(λ0(λλ201))"
  , db! "λ0(λλ201)(λ0(λλ201))" ]

set_option maxRecDepth 100000 in
theorem chainC3T2_check : betaChainCheck chainC3T2 = true := by decide

theorem betaStar_C3_T2 : C3 ↠βᶠ T2 :=
  betaChainCheck_sound chainC3T2 _ _ rfl rfl chainC3T2_check

/-- **`T₁ T₁ ↠βη T₂`.** -/
theorem betaEtaStar_T1T1 : (Term.app T1 T1) ↠βηᶠ T2 := by
  refine .trans (Relation.ReflTransGen.mono le_sup_left _ _ betaStar_T1T1_C1) ?_
  refine .trans (Relation.ReflTransGen.single (Or.inr fullEta_C1_C2)) ?_
  refine .trans (Relation.ReflTransGen.single (Or.inr fullEta_C2_C3)) ?_
  exact Relation.ReflTransGen.mono le_sup_left _ _ betaStar_C3_T2

/-- The two-step β-reduction `T₂ T₀ ↠β T₁ T₁`. -/
def chainT2T0 : List (Term String) :=
  [ db! "(λ0(λλ201)(λ0(λλ201)))(λλ0(λλ201))"
  , db! "(λλ0(λλ201))(λλ(λλ0(λλ201))01)(λ0(λλ201))"
  , db! "(λ0(λλ201))(λ0(λλ201))" ]

set_option maxRecDepth 100000 in
theorem chainT2T0_check : betaChainCheck chainT2T0 = true := by decide

theorem betaStar_T2T0 : (Term.app T2 T0) ↠βᶠ (Term.app T1 T1) :=
  betaChainCheck_sound chainT2T0 _ _ rfl rfl chainT2T0_check

/-- **`T₂ T₀ ↠βη T₂`.** -/
theorem betaEtaStar_T2T0 : (Term.app T2 T0) ↠βηᶠ T2 :=
  .trans (Relation.ReflTransGen.mono le_sup_left _ _ betaStar_T2T0) betaEtaStar_T1T1

/-- **`T₁ T₀ ↠βη T₁`.** -/
theorem betaEtaStar_T1T0 : (Term.app T1 T0) ↠βηᶠ T1 :=
  Relation.ReflTransGen.mono le_sup_left _ _ betaStar_T1T0

/-- **`T₀ M ↠βη T₁`** for every locally closed `M`. -/
theorem betaEtaStar_T0_app {M : Term String} (hM : LC M) : (Term.app T0 M) ↠βηᶠ T1 :=
  Relation.ReflTransGen.mono le_sup_left _ _ (betaStar_T0_app hM)

/-! ## The invariant -/

/-- `M` βη-reduces to one of the three values `T₀`, `T₁`, `T₂`. -/
def Val (M : Term String) : Prop := M ↠βηᶠ T0 ∨ M ↠βηᶠ T1 ∨ M ↠βηᶠ T2

/-- The invariant of the clone generated by `T₀`. -/
def Good (M : Term String) : Prop := Val M ∨ Bad M

/-- **The invariant is closed under application.** -/
theorem good_app {M N : Term String} (hlcN : LC N) (hM : Good M) (hN : Good N) :
    Good (Term.app M N) := by
  rcases hM with (hM | hM | hM) | ⟨M', hMs, hlcM', hnoM'⟩
  · -- `M ↠βη T₀`: the argument is discarded.
    refine Or.inl (Or.inr (Or.inl ?_))
    exact .trans (FullBetaEta.steps_app_l_cong hM hlcN) (betaEtaStar_T0_app hlcN)
  · -- `M ↠βη T₁`
    have hstep : Term.app M N ↠βηᶠ Term.app T1 N := FullBetaEta.steps_app_l_cong hM hlcN
    rcases hN with (hN | hN | hN) | ⟨N', hNs, hlcN', hnoN'⟩
    · refine Or.inl (Or.inr (Or.inl ?_))
      exact .trans (.trans hstep (FullBetaEta.steps_app_r_cong hN lc_T1)) betaEtaStar_T1T0
    · refine Or.inl (Or.inr (Or.inr ?_))
      exact .trans (.trans hstep (FullBetaEta.steps_app_r_cong hN lc_T1)) betaEtaStar_T1T1
    · refine Or.inr ⟨Term.app T1 T2, ?_, .app lc_T1 lc_T2, noHNFStack_T1T2⟩
      exact .trans hstep (FullBetaEta.steps_app_r_cong hN lc_T1)
    · refine Or.inr ⟨Term.app T1 N', ?_, .app lc_T1 hlcN', noHNFStack_T1_app hlcN' hnoN'⟩
      exact .trans hstep (FullBetaEta.steps_app_r_cong hNs lc_T1)
  · -- `M ↠βη T₂`
    have hstep : Term.app M N ↠βηᶠ Term.app T2 N := FullBetaEta.steps_app_l_cong hM hlcN
    rcases hN with (hN | hN | hN) | ⟨N', hNs, hlcN', hnoN'⟩
    · refine Or.inl (Or.inr (Or.inr ?_))
      exact .trans (.trans hstep (FullBetaEta.steps_app_r_cong hN lc_T2)) betaEtaStar_T2T0
    · refine Or.inr ⟨Term.app T2 T1, ?_, .app lc_T2 lc_T1, noHNFStack_T2T1⟩
      exact .trans hstep (FullBetaEta.steps_app_r_cong hN lc_T2)
    · refine Or.inr ⟨Term.app T2 T2, ?_, .app lc_T2 lc_T2, noHNFStack_T2T2⟩
      exact .trans hstep (FullBetaEta.steps_app_r_cong hN lc_T2)
    · refine Or.inr ⟨Term.app T2 N', ?_, .app lc_T2 hlcN', noHNFStack_T2_app hlcN' hnoN'⟩
      exact .trans hstep (FullBetaEta.steps_app_r_cong hNs lc_T2)
  · -- `M` is already diverging
    exact Or.inr ⟨Term.app M' N, FullBetaEta.steps_app_l_cong hMs hlcN, .app hlcM' hlcN,
      noHNFStack_app hnoM' hlcN⟩

theorem lc_of_gen {M : Term String} (h : Gen T0 M) : LC M := by
  refine genfinset_lc h ?_
  intro t ht
  simp only [List.mem_singleton] at ht
  exact ht ▸ lc_T0

/-- **Every applicative combination of `T₀` satisfies the invariant.** -/
theorem gen_good {M : Term String} (h : Gen T0 M) : Good M := by
  induction h with
  | base hmem =>
      rename_i a
      simp only [List.mem_singleton] at hmem
      exact Or.inl (Or.inl (hmem ▸ Relation.ReflTransGen.refl))
  | @app a b ha hb iha ihb => exact good_app (lc_of_gen hb) iha ihb

/-! ## The βη-normal forms reachable from the clone -/

theorem normal_T0 : Relation.Normal FullBetaEta T0 := by
  rw [← normal_fullBetaEta_iff_no_beta_eta_redex]; decide

theorem normal_T1 : Relation.Normal FullBetaEta T1 := by
  rw [← normal_fullBetaEta_iff_no_beta_eta_redex]; decide

theorem normal_T2 : Relation.Normal FullBetaEta T2 := by
  rw [← normal_fullBetaEta_iff_no_beta_eta_redex]; decide

/-- **The only βη-normal forms reachable from an applicative combination of
`T₀ = λλ0(λλ201)` are `T₀`, `T₁` and `T₂`.** -/
theorem gen_betaEtaStar_normal {M N : Term String} (hM : Gen T0 M) (h : M ↠βηᶠ N)
    (hn : Relation.Normal FullBetaEta N) : N = T0 ∨ N = T1 ∨ N = T2 := by
  rcases gen_good hM with (hV | hV | hV) | ⟨M', hMs, hlcM', hnoM'⟩
  · obtain ⟨Z, hZ1, hZ2⟩ := confluent_beta_eta hV h
    exact Or.inl (normal_T0.reflTransGen_eq (hn.reflTransGen_eq hZ2 ▸ hZ1)).symm
  · obtain ⟨Z, hZ1, hZ2⟩ := confluent_beta_eta hV h
    exact Or.inr (Or.inl (normal_T1.reflTransGen_eq (hn.reflTransGen_eq hZ2 ▸ hZ1)).symm)
  · obtain ⟨Z, hZ1, hZ2⟩ := confluent_beta_eta hV h
    exact Or.inr (Or.inr (normal_T2.reflTransGen_eq (hn.reflTransGen_eq hZ2 ▸ hZ1)).symm)
  · exfalso
    obtain ⟨Z, hZ1, hZ2⟩ := confluent_beta_eta hMs h
    have hM'N : M' ↠βηᶠ N := hn.reflTransGen_eq hZ2 ▸ hZ1
    exact hnoM' [] (by simp) (hasHNF_of_normalizable hlcM' ⟨N, hM'N, hn⟩)

/-- **No applicative combination of `T₀` βη-reduces to a βη-normal form other than `T₀`,
`T₁`, `T₂`.** -/
theorem gen_not_betaEtaStar {M y : Term String} (hM : Gen T0 M)
    (hy : Relation.Normal FullBetaEta y) (h0 : y ≠ T0) (h1 : y ≠ T1) (h2 : y ≠ T2) :
    ¬ (M ↠βηᶠ y) := by
  intro h
  rcases gen_betaEtaStar_normal hM h hy with rfl | rfl | rfl
  exacts [h0 rfl, h1 rfl, h2 rfl]

/-! ## `λλ0(λλ201)` is not a one-point basis -/

/-- **No applicative combination of `λλ0(λλ201)` βη-reduces to `I = λx. x`.** -/
theorem gen_not_betaEtaStar_I {M : Term String} (hM : Gen T0 M) : ¬ (M ↠βηᶠ I) :=
  gen_not_betaEtaStar hM normal_Icomb (by decide) (by decide) (by decide)

/-- **No applicative combination of `λλ0(λλ201)` βη-reduces to `K = λx y. x`.** -/
theorem gen_not_betaEtaStar_K {M : Term String} (hM : Gen T0 M) : ¬ (M ↠βηᶠ K) :=
  gen_not_betaEtaStar hM normal_K (by decide) (by decide) (by decide)

/-- **No applicative combination of `λλ0(λλ201)` is βη-*equal* to `I = λx. x`.**  This is
the conversion form of `gen_not_betaEtaStar_I`; the two agree because `I` is βη-normal and
βη is confluent. -/
theorem gen_not_eqv_I {M : Term String} (hM : Gen T0 M) :
    ¬ Relation.EqvGen FullBetaEta M I := fun h =>
  gen_not_betaEtaStar_I hM
    ((reflTransGen_iff_eqvGen_of_normal (by decide) (by decide)).mpr h)

/-- **No applicative combination of `λλ0(λλ201)` is βη-equal to `K = λx y. x`.** -/
theorem gen_not_eqv_K {M : Term String} (hM : Gen T0 M) :
    ¬ Relation.EqvGen FullBetaEta M K := fun h =>
  gen_not_betaEtaStar_K hM
    ((reflTransGen_iff_eqvGen_of_normal (by decide) (by decide)).mpr h)

/-- **`T = λλ0(λλ201)` is not a one-point basis for the λ-calculus under βη.** -/
theorem not_basis_0_lamlam201 : not_basis (db! "λλ0(λλ201)") := by
  refine ⟨I, by rw [← lcAt_iff_LC]; decide, by decide, ?_⟩
  intro t ht hred
  exact gen_not_betaEtaStar_I ht hred

end Term

end LambdaCalculus.LocallyNameless.Untyped

end Cslib
